global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

rule_files:
  - alerting-rules.yml

scrape_configs:
- job_name: postgres
  static_configs:
  - targets:
    - pgexporter:9187
